{
 "title": "Мониторинг API сервера AppNinjaBot",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "Application Name",
    "query": {
     "query": "label_values(fastapi_app_info{}, app_name)"
    }
   },
   { "name": "log_keyword", "label": "Log Query" }
  ]
 },
 "panels": [
  {
   "title": "Общее количество запросов",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(api_http_requests_total{job=\"api-server\", endpoint!=\"/metrics\"})"
    }
   ]
  },
  {
   "title": "Количество запросов по эндпоинтам",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "api_http_requests_total{job=\"api-server\", endpoint!=\"/metrics\"}",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Среднее время ответа запросов",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "api_http_request_duration_seconds_sum{job=\"api-server\"} / api_http_request_duration_seconds_count{job=\"api-server\"}",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Общее количество ошибок",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(api_http_requests_total{job=\"api-server\", status_code=~\"[45].*\", endpoint!=\"/metrics\"})"
    }
   ]
  },
  {
   "title": "Процент успешных запросов (2xx)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(path) (api_http_requests_total{job=\"api-server\", status_code=~\"2.*\", endpoint!=\"/metrics\"}) / sum by(path) (api_http_requests_total{job=\"api-server\", endpoint!=\"/metrics\"})",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Процент серверных ошибок (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(path) (api_http_requests_total{job=\"api-server\", status_code=~\"5.*\", endpoint!=\"/metrics\"}) / sum by(path) (api_http_requests_total{job=\"api-server\", endpoint!=\"/metrics\"})",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "99-й процентиль времени ответа",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99,sum(rate(api_http_request_duration_seconds_bucket{job=\"api-server\", endpoint!=\"/metrics\"}[1m])) by(path, le))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Запросы в обработке",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "api_http_requests_in_progress{job=\"api-server\", endpoint!=\"/metrics\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Запросы в секунду",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(api_http_requests_total{job=\"api-server\", endpoint!=\"/metrics\"}[1m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Log Type Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by(type) (rate({compose_service=~\"app-.*\"} | pattern `<date> <time> <type> <logger> <code> [<_>=<trace_id> <_>=<span_id> <_>=<service_name>] - <msg>` | type != \"\" |= \"$log_keyword\" [1m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Log of All FastAPI App",
   "type": "logs",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 21 },
   "targets": [
    {
     "expr": "{compose_service=~\"app-.*\"} | pattern `<date> <time> <type> <logger> <code> [<_>=<trace_id> <_>=<span_id> <_>=<service_name>] - <msg>` | line_format \"{{.compose_service}}\\t{{.type}}\\t trace_id={{.trace_id}}\\t {{.msg}}\" |= \"$log_keyword\""
    }
   ]
  }
 ]
}