"""add deactivate_from_date to shift_template_days

Revision ID: 000048
Revises: 000047
Create Date: 2025-11-20 16:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000048'
down_revision: Union[str, None] = '000047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_template_days', sa.Column('deactivate_from_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shift_template_days', 'deactivate_from_date')
    # ### end Alembic commands ###

