"""Add json_inventory column to groups table

Revision ID: 000006
Revises: 000005
Create Date: <TIMESTAMP> # Alembic добавит время автоматически

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # Импортируем для JSON

# revision identifiers, used by Alembic.
revision: str = '000006'
down_revision: Union[str, None] = '000005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('json_inventory', sa.JSON(), nullable=True, comment='Stores the actual inventory data as JSON'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'json_inventory')
    # ### end Alembic commands ### 