"""add notifications table

Revision ID: 000011
Revises: 000010 
Create Date: <TIMESTAMP> # Alembic подставит сам

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '000011'
down_revision: Union[str, None] = '000010' # Ссылается на предыдущую миграцию events
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('event_id', sa.Integer(), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('time', sa.Integer(), nullable=False, comment='Minutes before the event'),
        sa.Column('repeat_type', sa.String(), nullable=False, server_default='none', comment='Repeat type: none, daily, weekly, monthly'),
        sa.Column('repeat_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional repeat configuration (e.g., weekdays, month day)'),
        sa.Column('chat_ids', postgresql.ARRAY(sa.BigInteger()), nullable=True, comment='List of chat IDs to send the notification to'),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_notifications_event_id_events'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
        sa.CheckConstraint("repeat_type IN ('none', 'daily', 'weekly', 'monthly')", name=op.f('ck_notifications_repeat_type_values'))
    )
    op.create_index(op.f('ix_notifications_event_id'), 'notifications', ['event_id'], unique=False)
    # ### end Alembic commands ###

    # Добавляем триггер для обновления updated_at
    op.execute(
        """
        CREATE OR REPLACE FUNCTION trigger_set_timestamp()
        RETURNS TRIGGER AS $$
        BEGIN
          NEW.updated_at = NOW();
          RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER set_notifications_updated_at
        BEFORE UPDATE ON notifications
        FOR EACH ROW
        EXECUTE PROCEDURE trigger_set_timestamp();
        """
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_event_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
    # Удаляем триггер (хотя он может использоваться и другими таблицами, но для полноты)
    # Если функция используется другими таблицами, ее удалять не надо!
    # op.execute("DROP TRIGGER IF EXISTS set_notifications_updated_at ON notifications;")
    # op.execute("DROP FUNCTION IF EXISTS trigger_set_timestamp();") # Удалять только если больше нигде не нужна 