"""Add date field to write_offs table

Revision ID: 000022
Revises: 000021
Create Date: 2024-01-20 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '000022'
down_revision = '000021'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('write_offs', sa.Column('date', sa.Date(), server_default=sa.func.current_date(), nullable=False))
    
    # Обновляем существующие записи - устанавливаем дату на основе created_at
    op.execute("UPDATE write_offs SET date = DATE(created_at) WHERE date IS NULL")
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('write_offs', 'date')
    # ### end Alembic commands ### 