"""Add inventory_history table

Revision ID: 000007
Revises: 000006 
Create Date: <YYYY-MM-DD HH:MM:SS.mmmmmm> # Укажите текущую дату и время

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Убедитесь, что импортированы нужные типы, если используете специфичные для PostgreSQL
# import sqlalchemy_utils # Пример, если используется

# revision identifiers, used by Alembic.
revision: str = '000007'
down_revision: Union[str, None] = '000006' # ID предыдущей миграции
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=False),
        sa.Column('category', sa.String(), nullable=False),
        sa.Column('item_name', sa.String(), nullable=False),
        sa.Column('action', sa.String(), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('old_quantity', sa.Float(), nullable=True),
        sa.Column('new_quantity', sa.Float(), nullable=False),
        sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('author_id', sa.Integer(), nullable=True),
        # Внешние ключи
        sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_inventory_history_group_id_groups'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['author_id'], ['members.id'], name=op.f('fk_inventory_history_author_id_members'), ondelete='SET NULL'),
        # Первичный ключ
        sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_history'))
    )
    # Индексы
    op.create_index(op.f('ix_inventory_history_id'), 'inventory_history', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_history_group_id'), 'inventory_history', ['group_id'], unique=False)
    op.create_index(op.f('ix_inventory_history_category'), 'inventory_history', ['category'], unique=False)
    op.create_index(op.f('ix_inventory_history_item_name'), 'inventory_history', ['item_name'], unique=False)
    op.create_index(op.f('ix_inventory_history_timestamp'), 'inventory_history', ['timestamp'], unique=False)
    op.create_index(op.f('ix_inventory_history_author_id'), 'inventory_history', ['author_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_history_author_id'), table_name='inventory_history')
    op.drop_index(op.f('ix_inventory_history_timestamp'), table_name='inventory_history')
    op.drop_index(op.f('ix_inventory_history_item_name'), table_name='inventory_history')
    op.drop_index(op.f('ix_inventory_history_category'), table_name='inventory_history')
    op.drop_index(op.f('ix_inventory_history_group_id'), table_name='inventory_history')
    op.drop_index(op.f('ix_inventory_history_id'), table_name='inventory_history')
    op.drop_table('inventory_history')
    # ### end Alembic commands ###
