"""add violation fields to events

Revision ID: 000018
Revises: 000017
Create Date: 2025-05-19 16:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB


# revision identifiers, used by Alembic.
revision: str = '000018'
down_revision: Union[str, None] = '000017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('retailiqa_violation_count', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('retailiqa_detailed_violations', JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'retailiqa_detailed_violations')
    op.drop_column('events', 'retailiqa_violation_count')
    # ### end Alembic commands ### 