"""Add role to group_members and drop status from members

Revision ID: 000003 
Revises: 000002 
Create Date: 2025-04-12 23:30:00.000000 

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000003'
down_revision: Union[str, None] = '000002' # Ссылка на предыдущую миграцию
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Добавляем колонку 'role' в таблицу 'group_members'
    op.add_column('group_members', sa.Column('role', sa.String(length=50), server_default='member', nullable=False))
    
    # Удаляем колонку 'status' из таблицы 'members'
    # ВАЖНО: Сначала убедись, что данные из status не нужны или перенесены!
    # Если нужно сохранить старые статусы, можно сначала скопировать их в group_members.role
    # перед удалением колонки, но это усложнит миграцию.
    # Пока просто удаляем.
    op.drop_column('members', 'status')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Добавляем обратно колонку 'status' в 'members'
    op.add_column('members', sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'member'::character varying"), autoincrement=False, nullable=False))
    
    # Удаляем колонку 'role' из 'group_members'
    op.drop_column('group_members', 'role')
    
    # ### end Alembic commands ###
