"""add_supplies_config_to_groups

Revision ID: 000033
Revises: 000032
Create Date: 2025-09-16 12:00:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '000033'
down_revision: Union[str, None] = '000032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('supplies_config', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Configuration for supplies management: spreadsheet_id, sheet patterns, etc.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'supplies_config')
    # ### end Alembic commands ###
