"""add_retailiqa_object_name_to_groups_table

Revision ID: 000014
Revises: 000013
Create Date: 2025-05-19 10:00:00.000000+00:00 # Примерная дата, замените на актуальную

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000014'
down_revision: Union[str, None] = '000013' # Ссылается на предыдущую миграцию (000013)
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('retailiqa_object_name', sa.String(length=255), nullable=True))
    # Примечание: Индекс для этого поля пока не добавляем. 
    # Если потребуется, можно будет добавить отдельной миграцией или изменить эту.
    # Пример добавления индекса (если понадобится):
    # op.create_index(op.f('ix_groups_retailiqa_object_name'), 'groups', ['retailiqa_object_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Пример удаления индекса (если бы он был добавлен):
    # op.drop_index(op.f('ix_groups_retailiqa_object_name'), table_name='groups')
    op.drop_column('groups', 'retailiqa_object_name')
    # ### end Alembic commands ### 