"""add_ato_fields_to_events_table

Revision ID: 000013
Revises: 000012
Create Date: 2024-07-29 12:00:00.000000+00:00 # Примерная дата, замените на актуальную

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # Если используете JSONB или другие специфичные для PG типы

# revision identifiers, used by Alembic.
revision: str = '000013'
down_revision: Union[str, None] = '000012' # Ссылается на предыдущую миграцию
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_type', sa.String(), nullable=True))
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    
    op.add_column('events', sa.Column('retailiqa_insp_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_events_retailiqa_insp_id'), 'events', ['retailiqa_insp_id'], unique=True)
    
    op.add_column('events', sa.Column('retailiqa_insp_obj_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_events_retailiqa_insp_obj_id'), 'events', ['retailiqa_insp_obj_id'], unique=False)
    
    op.add_column('events', sa.Column('retailiqa_insp_obj_name', sa.String(), nullable=True))
    
    op.add_column('events', sa.Column('retailiqa_total_points', sa.Float(), nullable=True))
    op.add_column('events', sa.Column('retailiqa_penalty_points', sa.Float(), nullable=True))
    
    op.add_column('events', sa.Column('retailiqa_comments', sa.JSON(), nullable=True))
    op.add_column('events', sa.Column('retailiqa_photos', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'retailiqa_photos')
    op.drop_column('events', 'retailiqa_comments')
    op.drop_column('events', 'retailiqa_penalty_points')
    op.drop_column('events', 'retailiqa_total_points')
    op.drop_column('events', 'retailiqa_insp_obj_name')
    
    op.drop_index(op.f('ix_events_retailiqa_insp_obj_id'), table_name='events')
    op.drop_column('events', 'retailiqa_insp_obj_id')
    
    op.drop_index(op.f('ix_events_retailiqa_insp_id'), table_name='events')
    op.drop_column('events', 'retailiqa_insp_id')
    
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_column('events', 'event_type')
    # ### end Alembic commands ### 