"""add shift templates tables

Revision ID: 000035
Revises: 000034
Create Date: 2025-01-27 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '000035'
down_revision = '000034'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Создаем таблицу shift_templates
    op.create_table('shift_templates',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.String(length=1000), nullable=True),
        sa.Column('start_time', sa.Time(), nullable=False),
        sa.Column('end_time', sa.Time(), nullable=False),
        sa.Column('max_slots', sa.Integer(), nullable=False),
        sa.Column('has_senior_slot', sa.Boolean(), nullable=True),
        sa.Column('template_metadata', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['group_id'], ['groups.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_templates_group_id'), 'shift_templates', ['group_id'], unique=False)
    op.create_index(op.f('ix_shift_templates_name'), 'shift_templates', ['name'], unique=False)
    
    # Создаем таблицу shift_template_days
    op.create_table('shift_template_days',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('template_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=False),
        sa.Column('day_of_week', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['group_id'], ['groups.id']),
        sa.ForeignKeyConstraint(['template_id'], ['shift_templates.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_template_days_template_id'), 'shift_template_days', ['template_id'], unique=False)
    op.create_index(op.f('ix_shift_template_days_group_id'), 'shift_template_days', ['group_id'], unique=False)
    op.create_index(op.f('ix_shift_template_days_day_of_week'), 'shift_template_days', ['day_of_week'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Удаляем таблицы в обратном порядке
    op.drop_index(op.f('ix_shift_template_days_day_of_week'), table_name='shift_template_days')
    op.drop_index(op.f('ix_shift_template_days_group_id'), table_name='shift_template_days')
    op.drop_index(op.f('ix_shift_template_days_template_id'), table_name='shift_template_days')
    op.drop_table('shift_template_days')
    
    op.drop_index(op.f('ix_shift_templates_name'), table_name='shift_templates')
    op.drop_index(op.f('ix_shift_templates_group_id'), table_name='shift_templates')
    op.drop_table('shift_templates')
    
    # ### end Alembic commands ###
