"""add template_id to shifts

Revision ID: 000036
Revises: 3d1662c2a110
Create Date: 2025-10-23 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '000036'
down_revision = '3d1662c2a110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Добавляем поле template_id в таблицу shifts
    op.add_column('shifts', sa.Column('template_id', postgresql.UUID(as_uuid=True), nullable=True))
    
    # Добавляем внешний ключ к таблице shift_templates
    op.create_foreign_key(
        'fk_shifts_template_id',
        'shifts',
        'shift_templates',
        ['template_id'],
        ['id']
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Удаляем внешний ключ
    op.drop_constraint('fk_shifts_template_id', 'shifts', type_='foreignkey')
    
    # Удаляем поле template_id
    op.drop_column('shifts', 'template_id')
    
    # ### end Alembic commands ###
