"""add_retailiqa_score_fields_to_events

Revision ID: 000017
Revises: 000016
Create Date: 2024-05-20 10:00:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '000017'
down_revision: Union[str, None] = '000016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('retailiqa_score_percentage', sa.Float(), nullable=True))
    op.add_column('events', sa.Column('retailiqa_max_points', sa.Float(), nullable=True))
    op.add_column('events', sa.Column('retailiqa_earned_points', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'retailiqa_earned_points')
    op.drop_column('events', 'retailiqa_max_points')
    op.drop_column('events', 'retailiqa_score_percentage')
    # ### end Alembic commands ### 