"""Add requires_confirmation to notifications

Revision ID: 000012
Revises: 000011
Create Date: 2024-07-28 10:00:00.000000+00:00 # Примерная дата, замени если нужно

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000012'
down_revision: Union[str, None] = '000011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('requires_confirmation', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Does this notification require user confirmation?'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'requires_confirmation')
    # ### end Alembic commands ### 