"""Move is_senior_courier from members to group_members nullable

Revision ID: 000004
Revises: 000003
Create Date: 2025-04-13 00:00:00.000000 

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000004'
down_revision: Union[str, None] = '000003' 
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Добавляем колонку 'is_senior_courier' в таблицу 'group_members'
    # Делаем ее nullable=True, server_default убираем (будет NULL по умолчанию)
    op.add_column('group_members', sa.Column('is_senior_courier', sa.Boolean(), nullable=True)) 
    
    # Удаляем колонку 'is_senior_courier' из таблицы 'members'
    op.drop_column('members', 'is_senior_courier')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Добавляем обратно колонку 'is_senior_courier' в 'members'
    # nullable=False и server_default=false, как было изначально
    op.add_column('members', sa.Column('is_senior_courier', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    
    # Удаляем колонку 'is_senior_courier' из 'group_members'
    op.drop_column('group_members', 'is_senior_courier')
    
    # ### end Alembic commands ###
