"""Add access_settings column to groups table

Revision ID: 000005
Revises: 000004
Create Date: YYYY-MM-DD HH:MM:SS.ssssss # Поставь сюда текущую дату и время

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Если используешь PostgreSQL и хочешь JSONB, импортируй его:
# from sqlalchemy.dialects.postgresql import JSONB 

# revision identifiers, used by Alembic.
revision: str = '000005'
down_revision: Union[str, None] = '000004' # Предыдущая миграция
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Добавляем новую колонку 'access_settings' типа JSON в таблицу 'groups'
    # Если у тебя PostgreSQL, можешь заменить sa.JSON на JSONB(astext_type=sa.Text()) для лучшей производительности
    op.add_column('groups', sa.Column('access_settings', sa.JSON(), nullable=True, 
                                      comment='Isolated storage for shift access settings'))
    
    print("INFO: Added 'access_settings' column to 'groups' table.")
    
    # --- Важно! Перенос данных ---
    # Мы НЕ будем автоматически переносить данные из json_metadata в access_settings здесь.
    # Это безопаснее сделать через код приложения или отдельным скриптом,
    # чтобы точно скопировать только нужные ключи настроек.
    # Пока что новая колонка будет пустой (NULL).
    # Новые настройки будут сохраняться уже в нее.
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Удаляем колонку 'access_settings' из таблицы 'groups'
    op.drop_column('groups', 'access_settings')
    
    print("INFO: Dropped 'access_settings' column from 'groups' table.")
    
    # ### end Alembic commands ###