"""add_status_and_completed_at_to_notifications

Revision ID: 000015
Revises: 000014
Create Date: 2024-05-19 01:10:00.000000 

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '000015'
down_revision: Union[str, None] = '000014' # Ссылка на предыдущую миграцию
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('status', sa.String(), nullable=False, server_default='pending'))
    op.add_column('notifications', sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'completed_at')
    op.drop_column('notifications', 'status')
    # ### end Alembic commands ### 