"""Add is_senior_courier column to members table

Revision ID: 63dc19a320b9
Revises: a91108c08bf8
Create Date: 2025-04-05 22:15:10.999006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63dc19a320b9'
down_revision: Union[str, None] = 'a91108c08bf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_active_users_id', table_name='active_users')
    op.drop_index('ix_active_users_room', table_name='active_users')
    op.drop_index('ix_active_users_user_id', table_name='active_users')
    op.drop_table('active_users')
    op.drop_table('scheduler_tasks')
    op.add_column('members', sa.Column('is_senior_courier', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'is_senior_courier')
    op.create_table('scheduler_tasks',
    sa.Column('task_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('task_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('task_id', name='scheduler_tasks_pkey')
    )
    op.create_table('active_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('room', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('joined_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='active_users_pkey')
    )
    op.create_index('ix_active_users_user_id', 'active_users', ['user_id'], unique=False)
    op.create_index('ix_active_users_room', 'active_users', ['room'], unique=False)
    op.create_index('ix_active_users_id', 'active_users', ['id'], unique=False)
    # ### end Alembic commands ###
