"""Add group_type column to groups table

Revision ID: a91108c08bf8
Revises: abc894d43a47
Create Date: 2024-03-31 19:34:31.442724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a91108c08bf8'
down_revision: Union[str, None] = 'abc894d43a47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_index('ix_active_users_chat_id', table_name='active_users')
    except Exception as e:
        print(f"Ignored error when dropping index ix_active_users_chat_id: {e}")

    try:
        op.drop_table('active_users')
    except Exception as e:
        print(f"Ignored error when dropping table active_users: {e}")

    try:
        op.drop_table('scheduler_tasks')
    except Exception as e:
        print(f"Ignored error when dropping table scheduler_tasks: {e}")

    # Добавляем group_type
    op.add_column('groups', sa.Column('group_type', sa.String(length=50), nullable=True))
    # Заполняем поле group_type для существующих записей
    op.execute("UPDATE groups SET group_type = 'general' WHERE group_type IS NULL")
    op.alter_column('groups', 'group_type', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'group_type')
    op.create_table('active_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('first_activity', sa.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('last_activity', sa.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='active_users_pkey')
    )
    op.create_index('ix_active_users_chat_id', 'active_users', ['chat_id'], unique=False)
    op.create_table('scheduler_tasks',
    sa.Column('task_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('task_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('data', sa.JSON(), autoincrement=False, nullable=False, server_default=sa.text("'{}'::json")),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, server_default=sa.text('now()')),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, server_default=sa.text('now()')),
    sa.PrimaryKeyConstraint('task_id', name='scheduler_tasks_pkey')
    )
    # ### end Alembic commands ###
