"""Link Reserve to Member instead of User

Revision ID: ccca6cbe861b
Revises: 4b1bd84595e5
Create Date: 2025-04-07 17:07:52.545639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ccca6cbe861b'
down_revision: Union[str, None] = '4b1bd84595e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reserves',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('group_telegram_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reserves_date'), 'reserves', ['date'], unique=False)
    op.create_index(op.f('ix_reserves_group_telegram_id'), 'reserves', ['group_telegram_id'], unique=False)
    op.create_index(op.f('ix_reserves_member_id'), 'reserves', ['member_id'], unique=False)
    op.drop_table('scheduler_tasks')
    op.drop_index('ix_active_users_id', table_name='active_users')
    op.drop_index('ix_active_users_room', table_name='active_users')
    op.drop_index('ix_active_users_user_id', table_name='active_users')
    op.drop_table('active_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('room', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('joined_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='active_users_pkey')
    )
    op.create_index('ix_active_users_user_id', 'active_users', ['user_id'], unique=False)
    op.create_index('ix_active_users_room', 'active_users', ['room'], unique=False)
    op.create_index('ix_active_users_id', 'active_users', ['id'], unique=False)
    op.create_table('scheduler_tasks',
    sa.Column('task_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('task_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('task_id', name='scheduler_tasks_pkey')
    )
    op.drop_index(op.f('ix_reserves_member_id'), table_name='reserves')
    op.drop_index(op.f('ix_reserves_group_telegram_id'), table_name='reserves')
    op.drop_index(op.f('ix_reserves_date'), table_name='reserves')
    op.drop_table('reserves')
    # ### end Alembic commands ###
