"""change_reserve_group_telegram_id_to_group_id

Revision ID: e2fdf81c7c8a
Revises: ccca6cbe861b
Create Date: 2025-04-07 17:44:31.482868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2fdf81c7c8a'
down_revision: Union[str, None] = 'ccca6cbe861b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reserves', sa.Column('group_id', sa.Integer(), nullable=False))
    op.drop_index('ix_reserves_group_telegram_id', table_name='reserves')
    op.create_index(op.f('ix_reserves_group_id'), 'reserves', ['group_id'], unique=False)
    op.create_foreign_key(None, 'reserves', 'groups', ['group_id'], ['id'])
    op.drop_column('reserves', 'group_telegram_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reserves', sa.Column('group_telegram_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reserves', type_='foreignkey')
    op.drop_index(op.f('ix_reserves_group_id'), table_name='reserves')
    op.create_index('ix_reserves_group_telegram_id', 'reserves', ['group_telegram_id'], unique=False)
    op.drop_column('reserves', 'group_id')
    # ### end Alembic commands ###
