apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  labels:
    app: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
      - name: scheduler
        image: appninjabot-scheduler:latest
        imagePullPolicy: Never
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: API_URL
          value: "http://server-service:8000/api" 