# backend/API server/Dockerfile.dev

# Используем slim-образ Python для уменьшения размера
FROM python:3.11-slim as development

# Устанавливаем переменные окружения
ENV PYTHONDONTWRITEBYTECODE 1  
# Выводить логи сразу
ENV PYTHONUNBUFFERED 1         
# Отключить кеш pip внутри образа
ENV PIP_NO_CACHE_DIR=off       
# Если бы использовали Poetry
ENV POETRY_NO_INTERACTION=1    

# Устанавливаем рабочую директорию
WORKDIR /app

# Обновляем pip и устанавливаем зависимости
COPY ./requirements.txt /app/requirements.txt
RUN apt-get update && apt-get install -y bash curl ffmpeg && \
    pip install --upgrade pip && \
    pip install --no-cache-dir -r /app/requirements.txt && \
    # Устанавливаем psycopg2-binary и asyncpg здесь, чтобы они были в образе
    pip install --no-cache-dir psycopg2-binary asyncpg && \
    # Устанавливаем gunicorn для тестирования производительности
    pip install --no-cache-dir gunicorn
    # Установка alembic будет происходить из requirements.txt, который мы обновили


# Указываем порт, который будет слушать приложение 
EXPOSE 8000

# Команда по умолчанию (будет переопределена в docker-compose.yml)
# Для тестирования производительности используем gunicorn с 8 воркерами
CMD ["gunicorn", "main:app", "-b", "0.0.0.0:8000", "--workers", "8", "--timeout", "120", "-k", "uvicorn.workers.UvicornWorker"] 